    // Unexpire passwords to simplify dev mode. Comment these two lines for Production use
    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")

    ; enabling callin for Embedded Python
    do ##class(Security.Services).Get("%Service_CallIn",.prop)
    set prop("Enabled")=1
    set prop("AutheEnabled")=48
    do ##class(Security.Services).Modify("%Service_CallIn",.prop)

    // create IRISAPP namespace
    do $SYSTEM.OBJ.Load("/home/irisowner/irisdev/Installer.cls", "ck")
    set sc = ##class(App.Installer).setup()

    // Install samples BI
    zn "IRISAPP"
    zpm "load /home/irisowner/irisdev/.deps/Cache-MDX2JSON -v"
    zpm "load /home/irisowner/irisdev/.deps/Samples-BI -v"

    // load all the code of the project as a ZPM package
    zn "IRISAPP"
    zpm "load /home/irisowner/irisdev/ -v":1:1

    // Load iris-bi-utils and restore exported BI artefacts from the repo
    set sc = $System.OBJ.LoadDir("/home/irisowner/irisdev/.deps/iris-bi-utils/src/BIInstruments","ck",1)
    do:$SYSTEM.Status.IsError(sc) $SYSTEM.Status.DisplayError(sc)
    set biDir = "/home/irisowner/irisdev/bi/IRISAPP/"
    do ##class(BIInstruments.utils).workdir(biDir)
    if ##class(%File).DirectoryExists(biDir) {
        do ##class(BIInstruments.import).import("*.*","cku-d",.err,1,.loaded,1)
    }
    halt
